apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - secrets.yaml
  - cnpg.yaml
  - deploy.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml
  - pushsecret-oidc.yaml
  - oauth2-proxy
