apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-config
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: seerr-config
    template:
      engineVersion: v2
      data:
        sessionSecret: "{{ randAlphaNum 32 }}"
