apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-config
spec:
  refreshInterval: '0'
  target:
    name: seerr-config
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: seerr-session-key
      rewrite:
        - regexp:
            source: 'password'
            target: 'sessionSecret'
