apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-oauth2-proxy-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sonarr-oauth2-proxy-secrets
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: secrets-production/oauth2-proxy/config
        property: cookie-secret
