apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-config
data:
  TZ: "Europe/Paris"
  PLAYERS: "16"
  PORT: "8211"
  QUERY_PORT: "27015"
  REST_API_PORT: "8212"
  PUID: "1000"
  PGID: "1000"

  MULTITHREADING: "true"
  COMMUNITY: "true"

  PUBLIC_IP: "147.185.221.225"
  PUBLIC_PORT: "53228"

  SERVER_NAME: "RPCU Palworld Server"
  SERVER_DESCRIPTION: "RPCU Palworld Dedicated Server"

  UPDATE_ON_BOOT: "true"

  RCON_ENABLED: "true"
  RCON_PORT: "25575"

  BACKUP_ENABLED: "true"
  DELETE_OLD_BACKUPS: "false"
  OLD_BACKUP_DAYS: "30"
  BACKUP_CRON_EXPRESSION: "0 0 * * *"

  AUTO_UPDATE_ENABLED: "false"
  AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *"
  AUTO_UPDATE_WARN_MINUTES: "30"

  AUTO_REBOOT_ENABLED: "false"
  AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: "false"
  AUTO_REBOOT_WARN_MINUTES: "5"
  AUTO_REBOOT_CRON_EXPRESSION: "0 0 * * *"

  ENABLE_PLAYER_LOGGING: "false"
  PLAYER_LOGGING_POLL_PERIOD: "5"

  DIFFICULTY: "Normal"

  DAYTIME_SPEEDRATE: "1.000000"
  NIGHTTIME_SPEEDRATE: "1.000000"
  EXP_RATE: "1.000000"

  PAL_CAPTURE_RATE: "1.000000"
  PAL_SPAWN_NUM_RATE: "1.000000"
  PAL_DAMAGE_RATE_ATTACK: "1.000000"
  PAL_DAMAGE_RATE_DEFENSE: "1.000000"
  PAL_EGG_DEFAULT_HATCHING_TIME: "0.000000"
  PLAYER_DAMAGE_RATE_ATTACK: "1.000000"
  PLAYER_DAMAGE_RATE_DEFENSE: "1.000000"
  DEATH_PENALTY: "None"
  WORK_SPEED_RATE: "5.000000"
