apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: palworld-secrets
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: secrets-production/palworld/config
        property: ADMIN_PASSWORD
    - secretKey: SERVER_PASSWORD
      remoteRef:
        key: secrets-production/palworld/config
        property: SERVER_PASSWORD
    - secretKey: PLAYIT_SECRET_KEY
      remoteRef:
        key: secrets-production/palworld/config
        property: PLAYIT_SECRET_KEY
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: secrets-production/palworld/config
        property: DISCORD_WEBHOOK_URL
