apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-discord
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: palworld-discord
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: secrets-production/palworld/config
        property: DISCORD_WEBHOOK_URL
