apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: bazarr-oidc
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: bazarr-oidc
  data:
    - match:
        secretKey: attribute.client_id
        remoteRef:
          remoteKey: secrets-production/bazarr/oidc
          property: clientId
    - match:
        secretKey: attribute.client_secret
        remoteRef:
          remoteKey: secrets-production/bazarr/oidc
          property: clientSecret
