resources:
  - gitrepository.yaml
  - flux-kustomization.yaml
  - kgateway.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - crossplane.yaml
  - crossplane-zitadel.yaml
  - crossplane-resources.yaml
  - jellyfin
  - jellyswarrm
