resources:
  - gitrepository.yaml
  - flux-kustomization.yaml
  - kgateway.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - cnpg.yaml
  - crossplane.yaml
  - crossplane-zitadel.yaml
  - crossplane-resources.yaml
  - jellyfin
  - radarr
  - prowlarr
  - qbittorrent
  - sonarr
  - seerr
  - bazarr
  - jellystat
  - jellysweep
