# TODO: Adapt lifecycle and volume mounts to production
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels: &default
    app: jellyfin
    role: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *default
  template:
    metadata:
      labels: *default
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: jellyfin
          env:
            - name: MALLOC_TRIM_THRESHOLD_
              value: "100000"
            - name: DOTNET_SYSTEM_IO_DISABLESTATX
              value: "1"
          resources:
            requests:
              memory: 1000Mi
              cpu: 100m
            limits:
              # TODO: Adapt GPU
              # gpu.intel.com/i915: 1
              memory: 2000Mi
          image: docker.io/jellyfin/jellyfin:10.11.11
          ports:
            - containerPort: 8096
              name: jellyfin
          readinessProbe:
            httpGet:
              path: /health
              port: jellyfin
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: jellyfin
            initialDelaySeconds: 10
            periodSeconds: 20
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    sed -i 's/enableThemeSongs:function(){return w}/enableThemeSongs:function(){return _}/g' /jellyfin/jellyfin-web/main.jellyfin.bundle.js
                    sed -i 's/this.get("libraryPageSize",!1),10);return 0===t?0:t||100}/this.get("libraryPageSize",!1),10);return 0===t?0:t||0}/g' /jellyfin/jellyfin-web/main.jellyfin.bundle.js
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
            - name: media
              mountPath: /tvshows
              subPath: tvshows
            - name: media
              mountPath: /animes
              subPath: animes
            - name: media
              mountPath: /movies
              subPath: movies
            - name: transcodes
              mountPath: /transcodes
            - name: configjson
              mountPath: /jellyfin/jellyfin-web/config.json
              subPath: config.json
            - name: customcss
              mountPath: /jellyfin/jellyfin-web/custom.css
              subPath: custom.css
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: cache
          persistentVolumeClaim:
            claimName: cache
        - name: transcodes
          persistentVolumeClaim:
            claimName: transcodes
        - name: configjson
          configMap:
            name: jellyfin
            items:
              - key: config.json
                path: config.json
        - name: customcss
          configMap:
            name: jellyfin-css
            items:
              - key: custom.css
                path: custom.css
