apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deploy.yaml
  - service.yaml
  - httproute.yaml
  - namespace.yaml
  - cm.yaml
  - custom-css-cm.yaml
  - pvc.yaml
  - pushsecret-oidc.yaml
