apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: openchoreo-thunderid
spec:
  forProvider:
    accessTokenRoleAssertion: true
    accessTokenType: OIDC_TOKEN_TYPE_JWT
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
      - OIDC_GRANT_TYPE_REFRESH_TOKEN
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: true
    name: openchoreo-thunderid
    orgId: "369994019545117645"
    postLogoutRedirectUris:
      - "*"
    projectId: "370001231734928333" # adminstration
    redirectUris:
      - https://thunderid.platform.rpcu.lan/gate/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: openchoreo-thunderid-oidc
    namespace: crossplane-system
