apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: sonarr
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: sonarr
    orgId: "369994019545117645"
    postLogoutRedirectUris:
      - "*"
    projectId: "370001231734928333" # administration
    redirectUris:
      - https://sonarr.production.rpcu.lan/oauth2/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: sonarr-oidc
    namespace: media
