apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: seerr
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: seerr
    orgId: "369994019545117645"
    postLogoutRedirectUris:
      - "*"
    projectId: "370001231784969038" # public
    redirectUris:
      - https://seerr.rpcu.io/login
      - https://seerr.rpcu.io/api/v1/auth/oidc/callback/zitadel
      - https://seerr.rpcu.io/profile/settings/linked-accounts
      - https://seerr.rpcu.io/users/\d/settings/linked-accounts
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: seerr-oidc
    namespace: media
