apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rpcuio
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vhvictorhang@gmail.com
    privateKeySecretRef:
      name: external
    solvers:
      - dns01:
          cloudflare:
            email: vhvictorhang@gmail.com
            apiKeySecretRef:
              name: cert-manager-cloudflare-external
              key: api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-external
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cert-manager-cloudflare-external
  data:
    - secretKey: api-key
      remoteRef:
        key: secrets-production/cloudflare/api
        property: api-key
