apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-wg
  data:
    - secretKey: wg0.conf
      remoteRef:
        key: secrets-production/qbittorrent/config
        property: wg0.conf
